#!/usr/bin/env python3
"""
extract_images.py — emit a DLL's .data section as one C byte array.

WHY
---
The narrate pipeline (src/narrate.c, src/duration_eng.c, ...) reads a dozen
tables that sit next to each other in .data: the phoneme-name pair lists, the
voice table, a language's phoneme definitions, class words, rewrite rules and
voice rows. Extracting each one separately means hardcoding a size for every
table the original never bounds. Emitting the section whole keeps every table
at its original distance from its neighbours, so an over-read in the
reconstruction reads the same bytes the original would.

Same contract as the other extractors: runs at BUILD TIME against a DLL the
user owns, writes into the build tree, never committed. The DLL is parsed as
a file, never mapped or executed.

USAGE
    extract_images.py TIBASE32.DLL out/base_image.c --symbol sv_base_image
    extract_images.py TIENG32.DLL  out/eng_image.c  --symbol sv_eng_image --language \
        --text-range 1c205fb9:1c206780 --text-range 1c209c20:1c249310

With --language, the module descriptor LoadLanguage publishes (+0x04..+0x24)
is decoded out of LoadLanguage's own stores, as extract_generator.py does, and
emitted as `<symbol>_desc`.

Each --text-range is a run of read-only tables the module keeps inside .text
(the generator's interpolation and dB tables; the character classes, letter-
to-sound rules and exception dictionary). They are emitted as the array
`const sv_image <symbol>_text[]` with `<symbol>_text_count` entries.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from extract_generator import Image, descriptor_fields  # noqa: E402


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dll")
    ap.add_argument("out")
    ap.add_argument("--symbol", required=True)
    ap.add_argument("--language", action="store_true")
    ap.add_argument("--text-range", action="append", default=[],
                    help="LO:HI (hex VAs) of tables embedded in .text; repeatable")
    a = ap.parse_args()

    img = Image(a.dll)
    name, va, vsize, rawsize, rawoff = img.section(".data")
    data = img.read(va, vsize)

    with open(a.out, "w") as f:
        f.write("/* Generated by tools/extract_images.py from %s. DO NOT COMMIT.\n"
                " * SoftVoice, Inc. data, extracted from a user-supplied copy. */\n"
                % os.path.basename(a.dll))
        f.write("#include <stdint.h>\n")
        if a.text_range:
            f.write("#include \"tispeech/narrate.h\"\n")
        f.write("\n")
        f.write("const uint32_t %s_va = 0x%08xu;\n" % (a.symbol, va))
        f.write("const uint32_t %s_size = 0x%xu;\n" % (a.symbol, len(data)))
        f.write("const uint8_t %s[0x%x] = {\n" % (a.symbol, len(data)))
        for i in range(0, len(data), 16):
            f.write("    " + ",".join("0x%02x" % b for b in data[i:i + 16]) + ",\n")
        f.write("};\n")
        segs = []
        for k, r in enumerate(a.text_range):
            lo, hi = (int(x, 16) for x in r.split(":"))
            t = img.read(lo, hi - lo)
            f.write("\n/* Tables embedded in .text, 0x%08x..0x%08x. */\n" % (lo, hi))
            f.write("static const uint8_t text%d[0x%x] = {\n" % (k, len(t)))
            for i in range(0, len(t), 16):
                f.write("    " + ",".join("0x%02x" % b for b in t[i:i + 16]) + ",\n")
            f.write("};\n")
            segs.append((k, lo, len(t)))
        if segs:
            f.write("\nconst sv_image %s_text[%d] = {\n" % (a.symbol, len(segs)))
            for k, lo, n in segs:
                f.write("    {text%d, 0x%08xu, 0x%xu},\n" % (k, lo, n))
            f.write("};\nconst size_t %s_text_count = %d;\n" % (a.symbol, len(segs)))
        if a.language:
            d = descriptor_fields(img)
            vals = [d.get(off, 0) for off in range(0, 0x28, 4)]
            f.write("\n/* LoadLanguage's descriptor, offsets +0x00..+0x24. */\n")
            f.write("const uint32_t %s_desc[10] = {\n    %s\n};\n"
                    % (a.symbol, ", ".join("0x%08xu" % v for v in vals)))


if __name__ == "__main__":
    main()
